name: flashchat_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.5
  flutter:
    sdk: flutter
  modal_progress_hud_nsn: ^0.3.0
  shared_preferences: ^2.0.17

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/logo.png
    - images/download.png
    - images/appicon.png